package setup

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"github.com/ba0f3/luna-ztrust/proxy/internal/config"
)

// ErrConfigExists is returned when proxy.yml exists and Force is false.
var ErrConfigExists = errors.New("proxy config already exists")

// ProxyConfigOptions configures writing luna-proxy proxy.yml.
type ProxyConfigOptions struct {
	Path        string
	Force       bool
	EnrollToken string
	ListenAddr  string
	SignerMode  string
	User        string
	Group       string
}

// ProxyConfigResult describes a written proxy.yml.
type ProxyConfigResult struct {
	Path        string
	EnrollToken string
	Created     bool
}

// GenerateEnrollToken returns a random hex bootstrap secret for mtls_enroll_token.
func GenerateEnrollToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate enroll token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// WriteProxyConfig writes proxy.yml with mtls_enroll_token and production defaults.
func WriteProxyConfig(opts ProxyConfigOptions) (ProxyConfigResult, error) {
	opts = opts.withDefaults()
	path := opts.Path

	if !opts.Force {
		if _, err := os.Stat(path); err == nil {
			return ProxyConfigResult{}, fmt.Errorf("%w: %s", ErrConfigExists, path)
		}
	}

	token := strings.TrimSpace(opts.EnrollToken)
	if token == "" {
		var err error
		token, err = GenerateEnrollToken()
		if err != nil {
			return ProxyConfigResult{}, err
		}
	}

	body := renderProxyConfig(token, opts)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return ProxyConfigResult{}, fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := writeFileAtomic(path, []byte(body), 0o600); err != nil {
		return ProxyConfigResult{}, err
	}
	if opts.User != "" {
		if err := chownProxyConfig(path, opts.User, opts.Group); err != nil {
			return ProxyConfigResult{}, err
		}
	}
	return ProxyConfigResult{Path: path, EnrollToken: token, Created: true}, nil
}

func (o ProxyConfigOptions) withDefaults() ProxyConfigOptions {
	if strings.TrimSpace(o.Path) == "" {
		o.Path = config.DefaultProxyConfigPath
	}
	o.Path = filepath.Clean(o.Path)
	if o.ListenAddr == "" {
		o.ListenAddr = ":8443"
	}
	if o.SignerMode == "" {
		o.SignerMode = "local-ca"
	}
	if o.Group == "" && o.User != "" {
		o.Group = o.User
	}
	return o
}

func renderProxyConfig(enrollToken string, opts ProxyConfigOptions) string {
	escaped := strings.ReplaceAll(enrollToken, `"`, `\"`)
	return fmt.Sprintf(`# Luna Z-Trust — luna-proxy
# Generated by luna-proxy setup (config / mtls --write-config / install systemd).
# mTLS cert paths default to %s/ after: luna-proxy setup mtls
#
# Agent hosts use mtls_enroll_token to obtain client.crt:
#   export LUNA_MTLS_ENROLL_TOKEN='%s'
#   luna-agent setup

listen_addr: %q
control_socket: %q
control_socket_group: luna-admin
signer_mode: %q
approval_timeout: 60s

mtls_enroll_token: "%s"

# Telegram OOB approval (required when env is not dev)
# telegram_bot_token: ""
# telegram_webhook_secret: ""
# telegram_chat_id: ""
`, config.DefaultCertsDir, enrollToken, opts.ListenAddr, config.ProductionControlSocket, opts.SignerMode, escaped)
}

func chownProxyConfig(path, username, group string) error {
	u, err := user.Lookup(username)
	if err != nil {
		return nil
	}
	g, err := user.LookupGroup(group)
	if err != nil {
		return nil
	}
	var uid, gid int
	if _, err := fmt.Sscanf(u.Uid, "%d", &uid); err != nil {
		return nil
	}
	if _, err := fmt.Sscanf(g.Gid, "%d", &gid); err != nil {
		return nil
	}
	if err := os.Chown(path, uid, gid); err != nil {
		return fmt.Errorf("chown %s: %w", path, err)
	}
	return nil
}
