package setup

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"os/user"
	"path/filepath"
	"strings"

	"github.com/ba0f3/luna-ztrust/proxy/internal/config"
)

// ErrConfigExists is returned when proxy.yml exists and Force is false.
var ErrConfigExists = errors.New("proxy config already exists")

// ProxyConfigOptions configures writing luna-proxy proxy.yml.
type ProxyConfigOptions struct {
	Path                  string
	Force                 bool
	EnrollToken           string
	Env                   string
	Hostname              string
	ListenAddr            string
	SignerMode            string
	KeyPath               string
	TelegramBotToken      string
	TelegramWebhookSecret string
	TelegramChatID        string
	ControlSocket         string
	ControlSocketGroup    string
	AdminClientOU         string
	ApprovalTimeout       string
	User                  string
	Group                 string
}

// ProxyConfigResult describes a written proxy.yml.
type ProxyConfigResult struct {
	Path        string
	EnrollToken string
	Created     bool
}

// GenerateEnrollToken returns a random hex bootstrap secret for mtls_enroll_token.
func GenerateEnrollToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate enroll token: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// WriteProxyConfig writes proxy.yml with production defaults.
func WriteProxyConfig(opts ProxyConfigOptions) (ProxyConfigResult, error) {
	opts = opts.withDefaults()
	path := opts.Path

	if !opts.Force {
		if _, err := os.Stat(path); err == nil {
			return ProxyConfigResult{}, fmt.Errorf("%w: %s", ErrConfigExists, path)
		}
	}

	token := strings.TrimSpace(opts.EnrollToken)
	if token == "" {
		var err error
		token, err = GenerateEnrollToken()
		if err != nil {
			return ProxyConfigResult{}, err
		}
	}

	body := renderProxyConfig(token, opts)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return ProxyConfigResult{}, fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := writeFileAtomic(path, []byte(body), 0o600); err != nil {
		return ProxyConfigResult{}, err
	}
	if opts.User != "" {
		if err := chownProxyConfig(path, opts.User, opts.Group); err != nil {
			return ProxyConfigResult{}, err
		}
	}
	return ProxyConfigResult{Path: path, EnrollToken: token, Created: true}, nil
}

func (o ProxyConfigOptions) withDefaults() ProxyConfigOptions {
	if strings.TrimSpace(o.Path) == "" {
		o.Path = config.DefaultProxyConfigPath
	}
	o.Path = filepath.Clean(o.Path)
	if o.Env == "" {
		o.Env = envProduction
	}
	if o.ListenAddr == "" {
		o.ListenAddr = ":8443"
	}
	if o.SignerMode == "" {
		o.SignerMode = "local-ca"
	}
	if o.KeyPath == "" {
		o.KeyPath = defaultKeyPath(o.SignerMode)
	}
	if o.ControlSocket == "" {
		o.ControlSocket = config.ProductionControlSocket
	}
	if o.ControlSocketGroup == "" {
		o.ControlSocketGroup = "luna-admin"
	}
	if o.AdminClientOU == "" {
		o.AdminClientOU = "luna-admin"
	}
	if o.ApprovalTimeout == "" {
		o.ApprovalTimeout = "60s"
	}
	if o.Group == "" && o.User != "" {
		o.Group = o.User
	}
	return o
}

func renderProxyConfig(enrollToken string, opts ProxyConfigOptions) string {
	yamlQuote := func(s string) string {
		return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
	}
	var b strings.Builder
	b.WriteString("# Luna Z-Trust — luna-proxy\n")
	b.WriteString("# Generated by luna-proxy setup\n")
	if opts.Hostname != "" {
		fmt.Fprintf(&b, "# Public hostname: %s (mTLS server certificate SAN)\n", opts.Hostname)
		fmt.Fprintf(&b, "# Agent proxy_url: %s\n", defaultPublicProxyURL(opts.Hostname, opts.ListenAddr))
	}
	b.WriteString("#\n")
	fmt.Fprintf(&b, "# Agent bootstrap: export LUNA_MTLS_ENROLL_TOKEN='%s'\n\n", enrollToken)

	fmt.Fprintf(&b, "env: %q\n\n", opts.Env)
	fmt.Fprintf(&b, "listen_addr: %q\n", opts.ListenAddr)
	fmt.Fprintf(&b, "control_socket: %q\n", opts.ControlSocket)
	fmt.Fprintf(&b, "control_socket_group: %q\n\n", opts.ControlSocketGroup)

	fmt.Fprintf(&b, "signer_mode: %q\n", opts.SignerMode)
	fmt.Fprintf(&b, "key_path: %q\n", opts.KeyPath)
	fmt.Fprintf(&b, "admin_client_ou: %q\n", opts.AdminClientOU)
	fmt.Fprintf(&b, "approval_timeout: %s\n\n", opts.ApprovalTimeout)

	fmt.Fprintf(&b, "telegram_bot_token: %s\n", yamlQuote(opts.TelegramBotToken))
	fmt.Fprintf(&b, "telegram_chat_id: %s\n\n", yamlQuote(opts.TelegramChatID))

	fmt.Fprintf(&b, "mtls_enroll_token: %s\n\n", yamlQuote(enrollToken))

	b.WriteString("# mTLS cert paths default to /etc/luna/certs/ after setup (override if --dir differs):\n")
	fmt.Fprintf(&b, "# mtls_server_cert: %s/server.crt\n", config.DefaultCertsDir)
	fmt.Fprintf(&b, "# mtls_server_key: %s/server.key\n", config.DefaultCertsDir)
	fmt.Fprintf(&b, "# mtls_client_ca: %s/ca.crt\n", config.DefaultCertsDir)
	fmt.Fprintf(&b, "# mtls_ca_cert_path: %s/ca.crt\n", config.DefaultCertsDir)
	fmt.Fprintf(&b, "# mtls_ca_key_path: %s/ca.key\n", config.DefaultCertsDir)
	return b.String()
}

func chownProxyConfig(path, username, group string) error {
	u, err := user.Lookup(username)
	if err != nil {
		return nil
	}
	g, err := user.LookupGroup(group)
	if err != nil {
		return nil
	}
	var uid, gid int
	if _, err := fmt.Sscanf(u.Uid, "%d", &uid); err != nil {
		return nil
	}
	if _, err := fmt.Sscanf(g.Gid, "%d", &gid); err != nil {
		return nil
	}
	if err := os.Chown(path, uid, gid); err != nil {
		return fmt.Errorf("chown %s: %w", path, err)
	}
	return nil
}
