package install

import (
	"fmt"
	"os"
	"os/user"
	"path/filepath"

	"github.com/ba0f3/luna-ztrust/proxy/internal/config"
)

const defaultProxyConfigContent = `# Luna Z-Trust — luna-proxy (generated by: luna-proxy install systemd)
# mTLS paths default to /etc/luna/certs/ after setup mtls. Edit Telegram and signer_mode as needed.

listen_addr: ":8443"
control_socket: /run/luna/control.sock
control_socket_group: luna-admin
signer_mode: local-ca
approval_timeout: 60s
`

// EnsureDefaultProxyConfig writes a minimal proxy.yml when missing.
func EnsureDefaultProxyConfig(path, username, group string) error {
	if path == "" {
		path = config.DefaultProxyConfigPath
	}
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("stat %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(defaultProxyConfigContent), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	if err := chownFile(path, username, group); err != nil {
		return err
	}
	fmt.Printf("wrote default config %s\n", path)
	return nil
}

func chownFile(path, username, group string) error {
	u, err := user.Lookup(username)
	if err != nil {
		return nil
	}
	g, err := user.LookupGroup(group)
	if err != nil {
		return nil
	}
	var uid, gid int
	if _, err := fmt.Sscanf(u.Uid, "%d", &uid); err != nil {
		return nil
	}
	if _, err := fmt.Sscanf(g.Gid, "%d", &gid); err != nil {
		return nil
	}
	if err := os.Chown(path, uid, gid); err != nil {
		return fmt.Errorf("chown %s: %w", path, err)
	}
	return nil
}
