package setup

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ConfigOptions holds agent.yml fields.
type ConfigOptions struct {
	Path               string
	ProxyURL           string
	SignerMode         string
	CertsDir           string
	TargetUser         string
	TargetHost         string
	AgentSocket        string
	HostKeyFingerprint string
	Force              bool
}

// WriteAgentConfig writes /etc/luna/agent.yml (or Path).
func WriteAgentConfig(opts ConfigOptions) (string, error) {
	opts = opts.withDefaults()
	if !opts.Force {
		if _, err := os.Stat(opts.Path); err == nil {
			return opts.Path, nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(opts.Path), 0o750); err != nil {
		return "", fmt.Errorf("mkdir config dir: %w", err)
	}
	body := fmt.Sprintf(`# Luna Z-Trust — luna-agent (generated by: luna-agent setup)
proxy_url: %s
signer_mode: %s

mtls_cert: %s/client.crt
mtls_key: %s/client.key
mtls_ca: %s/ca.crt

target_user: %s
target_host: %s
agent_socket: %s
`, opts.ProxyURL, opts.SignerMode, opts.CertsDir, opts.CertsDir, opts.CertsDir,
		opts.TargetUser, opts.TargetHost, opts.AgentSocket)
	if fp := strings.TrimSpace(opts.HostKeyFingerprint); fp != "" {
		body += fmt.Sprintf("host_key_fingerprint: %s\n", fp)
	}
	if err := writeFile(opts.Path, []byte(body), 0o600); err != nil {
		return "", err
	}
	return opts.Path, nil
}

func (o ConfigOptions) withDefaults() ConfigOptions {
	if o.Path == "" {
		o.Path = DefaultConfigPath
	}
	if o.CertsDir == "" {
		o.CertsDir = DefaultCertsDir
	}
	if o.AgentSocket == "" {
		o.AgentSocket = ProductionAgentSocket
	}
	if o.SignerMode == "" {
		o.SignerMode = "local-ca"
	}
	return o
}
